name: .NET & C++ Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.306'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Checkout vcpkg
      uses: actions/checkout@v4
      with:
        repository: "https://github.com/Microsoft/vcpkg"
        path: "vcpkg"

    - name: Setup vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
        ${{ github.workspace }}/vcpkg/vcpkg install wil:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg integrate install

    - name: Install Windows 10 SDK (10.0.19041.0)
      run: choco install windows-sdk-10-version-2004-all -y --no-progress

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build solution
      run: msbuild CaptureTool.sln /p:Configuration=Release /p:Platform=x64 /m

    - name: Run .NET tests
      run: dotnet test --no-build --verbosity normal
